import ThemeProvider from '@/Contexts/ThemeProvider'
import '../styles/globals.css'
import { Inter } from 'next/font/google'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function MyApp({ Component, pageProps }) {
  return (
    <ThemeProvider>
      <Component
        {...pageProps} />
    </ThemeProvider>
  )
}
